platform :ios, '8.0'
target 'individual' do
pod 'AFNetworking'
pod 'YYText'
pod 'pop', '~> 1.0.7'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'Bugly'
pod 'Masonry'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MGSwipeTableCell', '~> 1.5.6'
pod 'EAIntroView', '~> 2.10.0'
end
