source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'http://gitlab.buluo-gs.com/iOS/podspec.git'   # 私有库
platform :ios, '8.0'
target 'individual' do
pod 'TCCommonLibs'
pod 'YYText'
pod 'MBProgressHUD'
pod 'pop', '~> 1.0.7'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MGSwipeTableCell', '~> 1.5.6'
pod 'EAIntroView', '~> 2.10.0'
pod 'AMap2DMap-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'AMapLocation-NO-IDFA'
pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'Bugly'
pod 'WechatOpenSDK'
pod 'QQ_XGPush'
end
