platform :ios, '8.0'
target 'individual' do
pod 'AFNetworking', '~> 3.0'
pod 'YYText'
pod 'pop', '~> 1.0.7'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh', '~>3.1.12'
pod 'SDWebImage', '~> 4.0.0-beta2'
end
